# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: local
    hooks:
    -   id: black
        name: Black Python code formatting
        entry: bash -c 'black . -l 100 --target-version py36; git add -u'
        language: python
    -   id: autoflake
        name: Remove unused variables and imports
        entry: bash -c 'autoflake "$@"; git add -u'
        language: python
        args:
          [
            ".",
            "-r",
            "--in-place",
            "--remove-all-unused-imports",
            "--remove-unused-variables",
            "--expand-star-imports",
            "--ignore-init-module-imports",
          ]
        files: .py$
    -   id: isort
        name: Sort imports alphabetically
        entry: bash -c 'isort "$@"; git add -u'
        args: [".", "--profile", "black", "--filter-files", "--only-modified"]
        language: python